### ISSUE TITLE
[mux] A monitor for `wistia_77` has not been initialized.

### ISSUE THREAD

**Issue by cory4patriots** [wistia/wistia-api#30] opened 2019-07-08 15:28 UTC
I am getting the following error: `[mux] A monitor for `wistia_77` has not been initialized.`
Nuxt.js is the frontend tech that we are using. I have reached out to `Mux` and received the the following response. 

> Wistia uses our product to track the performance of their player and system, and that is a result of some of their code trying to track a specific event in the player, without first initializing our library correctly. The player may work fine, but something in their player is not working like they expect it to. Sorry to bump you over to Wistia, but without access to their player code, there's not much I can do.

Please let me know how to move forward on how to resolve this issue.

**Comment by MaxPower15** [comment] 2019-07-08 17:20
Hi @cory4patriots, I asked our support team if they received a report on this at support@wistia.com and they said yes. I'm closing this GitHub issue because it's not related to our wistia-api ruby gem, but you should expect a response to this issue in your email. Thanks!

**Closed as completed by MaxPower15** 2019-07-08 17:20 UTC

**Comment by pm-radu** [comment] 2021-06-17 21:41
@MaxPower15 Any chance you can share the solution, please? I am getting the same issue

**Comment by MaxPower15** [comment] 2021-06-17 23:24
@pm-radu I didn't track that ticket myself and don't know what the ultimate solution was. That said, having very little context, my suspicion is that it is caused by rapid re-renders in the virtual DOM. When that happens, the Wistia video elements get clobbered and cause it to reinitialize before it finishes setup. It can be solved in frameworks like React (and I assume Vue, too) by wrapping the video in a component that prevents updates, i.e. `shouldComponentUpdate() { return false; }`. If that doesn't sound like it would be related to your situation, I'd recommend also sending an email to support@wistia.com. They'll be able to take a closer look at your specific situation and escalate to engineers like me if they need to.
